### PR TITLE
fix: map related issues - crash, focus, complete hunts, focus on position on hunt creation

### LINKED ISSUE #265: Fix map related issues: crash, focus, complete hunts, focus on hunt creation

### PR DESCRIPTION
**Pull request by Matax606**
## User Story

**As a user, I want to be able to play hunts in order to discover new places.**

---

## Task Reference

**Tasks:** Fix map-related issues: crash, focus, complete hunts, focus on hunt creation (closes #265)
**Related:** Hunt creation UX improvements, Map UI consistency, Permission request flow

---

## Description

This PR reproposes the previous user-friendly camera-centering logic that mirrors what already exists in play mode.

The hunts completed are now saved on the profile as before, and the app no longer crashes upon requesting the location authorization.

Furthermore, when the user enters the Add Points map screen, their location is visible, and they can press the "focus" button to center the camera on their position. If it's the first time the app requests location access, the familiar permission pop-up appears.

---

### Map Behavior
 - Added user localization on the hunt creation screen using:
   - `fusedLocationClient`
   - `cameraPositionState.move(...)`
   - `MapScreenDefaults.UserLocationZoom`
- Introduced a `mapLoaded` flag to prevent early camera updates.
- Implemented a new `LaunchedEffect` coordinating:
  - permission status
  - map readiness
- Matched the behavior of MapScreen without duplicating permission UI logic.

### Permission Flow
- Screen now supports first-time permission prompt via `PermissionRequestPopup`.
- Ensures consistent UX across all map screens.

---

## Notes

This PR includes modifications to the CI that represent changes merged in the main branch (they are an exact match), and removes a non-deterministic test for the profile.

It is also impossible to meet the 80% line coverage criteria: most of the modifications are not testable with the tools at our disposal (Android's legacy localization pop-up, lambda execution when a marker is placed, etc.). Since all of our files in the app have very good coverage, it won't be an issue.

---

## Next Steps
- Automatically set the distance and time of a hunt.

---

## Checklist

- [x] Added fused-location camera centering logic
- [x] Implemented mapLoaded safety gate
- [x] Integrated camera move with existing permission flow
- [x] Synced user-recentering behavior with MapScreen
- [x] Verified backwards compatibility for existing hunts

---

Note: this pull request was developed with the use of AI.

### CODE REVIEW

File: app/src/androidTest/java/com/swentseekr/seekr/ui/profile/ProfileTest.kt [hunk 1]
```diff
@@ -12,7 +12,6 @@ import androidx.compose.ui.test.hasTestTag
 import androidx.compose.ui.test.hasText
 import androidx.compose.ui.test.junit4.createComposeRule
 import androidx.compose.ui.test.onAllNodesWithTag
-import androidx.compose.ui.test.onFirst
```
Comment (sofiaprofka00) [inline app/src/androidTest/java/com/swentseekr/seekr/ui/profile/ProfileTest.kt]: LGTM

File: app/src/main/java/com/swentseekr/seekr/ui/map/MapOverlays.kt [hunk 2]
```diff
@@ -15,7 +15,6 @@ import androidx.compose.runtime.Composable
 import androidx.compose.runtime.getValue
 import androidx.compose.runtime.mutableStateOf
 import androidx.compose.runtime.remember
```
Comment (sofiaprofka00) [inline app/src/main/java/com/swentseekr/seekr/ui/map/MapOverlays.kt]: LGTM

**Review by sofiaprofka00 — CHANGES_REQUESTED** [review]
Good job on this pr! Make sure to address the 6 SonarCloud issues on the different files and the few comments I put. Also the coverage is a bit low but understandable isnce testing your code is very difficult and you already spent much time on this. MAke sure to try again when implementing new things. Nice !

**Comment by Matax606** [comment]
Hey, thanks for the review. As you mentioned, it won't be possible for me to meet the 80% line coverage criteria, as the only lines that are not covered (from the additions of this pr) are not testable through instrumented tests. They are about authorization on localization and movement of the camera on the map, which until now have been avoided in tests, as they are, as said, untestable. In this pr, they just appear to represent a major part of the content as they were missing in the section about adding a checkpoint during the creation of a hunt. We have a very strong overall coverage among all files in the app, so this won't be an issue.
